INCLUDE ffl/tst.fs
INCLUDE puzzle03a.fs

T{ ." DIRECTIONS CAN BE ORTHOGONAL OR NOT" CR
    LEFT-DIR UP-DIR ORTHOGONAL?     TRUE  ?S
    LEFT-DIR RIGHT-DIR ORTHOGONAL?  FALSE ?S
    DOWN-DIR RIGHT-DIR ORTHOGONAL?  TRUE  ?S
    UP-DIR DOWN-DIR ORTHOGONAL?     FALSE ?S
}T


T{ ." WIRE WORDS COMPILE A WIRE IN A DIRECTION" CR
    CREATE WIRES
    8 WIRE-R 5 WIRE-U 5 WIRE-L 3 WIRE-D
    WIRES 0 CELLS + WIRE@ 8 ?S RIGHT-DIR ?S
    WIRES 1 CELLS + WIRE@ 5 ?S UP-DIR ?S
    WIRES 2 CELLS + WIRE@ 5 ?S LEFT-DIR ?S
    WIRES 3 CELLS + WIRE@ 3 ?S DOWN-DIR ?S
}T

: REVERSE-4-ARGS ( a,b,c,d -- d,c,b,a )
    SWAP 2SWAP SWAP ;
    
T{ ." WIRE>LINE CONVERT A LOCATION AND A WIRE INTO A LINE" CR
    100 200 RIGHT-DIR 8 WIRE>LINE
    REVERSE-4-ARGS
    RIGHT-DIR ?S 100 ?S 200 ?S 208 ?S

    100 200 UP-DIR 5 WIRE>LINE
    REVERSE-4-ARGS
    UP-DIR ?S 200 ?S 100 ?S 105 ?S

    100 200 LEFT-DIR 3 WIRE>LINE
    REVERSE-4-ARGS
    LEFT-DIR ?S 100 ?S 197 ?S 200 ?S

    100 200 DOWN-DIR 7 WIRE>LINE
    REVERSE-4-ARGS
    DOWN-DIR ?S 200 ?S 93 ?S 100 ?S
}T

BYE

