
16 CONSTANT WORD-BITS
1 WORD-BITS LSHIFT 1- CONSTANT WORD-MASK
1 WORD-BITS 1- LSHIFT CONSTANT SIGN-BIT
WORD-MASK -1 XOR CONSTANT NEGATIVE-CELL-MASK

: WORD>CELL ( w -- n )
    DUP SIGN-BIT AND IF
        NEGATIVE-CELL-MASK OR
    THEN ;

: <<WORD| ( n,w -- w:n )
    WORD-BITS LSHIFT SWAP WORD-MASK AND OR ;

: |WORD>> ( w -- n,w' )
    DUP WORD-MASK AND WORD>CELL
    SWAP WORD-BITS RSHIFT ;

: WIRE>CELL ( row,col,steps,dist? -- w )
      0 <<WORD| <<WORD| <<WORD| <<WORD| ;

: CELL>WIRE ( w -- row,col,steps,dist? )
    |WORD>> |WORD>> |WORD>> |WORD>> DROP ;

